### ISSUE TITLE
No API to push data

### ISSUE THREAD

**Issue by ghost** [mongoose-os-libs/blynk#2]
Even the library contains the **virtualWrite(conn, ...)** API, it is not possible to push data to _Blynk_ server in a _Timer_ callback. In fact, in this case, there are no ways to pass the conn parameter to the API.

With Best Regards,
Filippo Balestrini

**Comment by cpq** [comment]
Try this:

```
load('api_gpio.js');
load('api_blynk.js');
load('api_timer.js');

let bConn;  // Blynk connection, to be initialized by the setHandler

Blynk.setHandler(function(conn, cmd, pin, val, id) {
  bConn = conn;
}, null);

Timer.set(1000, 1, function() {
  if (!bConn) return;  // not yet initialized
  Blynk.send(....);
}, null);
```

**Comment by ghost** [comment]
Are you sure the blynk handler callback is invoked even if no "vr" or "vw" commands are triggered from the blynk app?

On Jan 31, 2018 17:55, Sergey Lyubka <notifications@github.com> wrote:

Try this:

load('api_gpio.js');
load('api_blynk.js');
load('api_timer.js');

let bConn;  // Blynk connection, to be initialized by the setHandler

Blynk.setHandler(function(conn, cmd, pin, val, id) {
  bConn = conn;
}, null);

Timer.set(1000, 1, function() {
  if (!bConn) return;  // not yet initialized
  Blynk.send(....);
}, null);
